DATABASE_FILE_NAME = "data/database.csv"
DATABASE_INDEX_NAME = 0
DATABASE_INDEX_EMAIL_ADDRESS = 1
DATABASE_INDEX_PHONE_NO = 2

WEBAPI_IP = "192.168.1.16:37001"
WEBAPI_URL = "http://" + WEBAPI_IP + "/api/data"
WEBAPI_URL_ALARM = "http://" + WEBAPI_IP + "/api/alarm"
WEBAPI_URL_ALARM_DISABLE = "http://" + WEBAPI_IP + "/api/disablealarm"
WEBAPI_URL_ALARM_ENABLE = "http://" + WEBAPI_IP + "/api/enablealarm"

EMAIL_API_STMP_HOST = "smtp-mail.outlook.com"
EMAIL_API_SMTP_PORT = 587
EMAIL_API_EMAIL_ADDRESS = "muhammedtiftikci@outlook.com"
EMAIL_API_EMAIL_PASSWORD = "326Qa30bb60"

SMS_API_USERNAME = ""
SMS_API_ORIGINATOR = ""
SMS_API_PASSWORD = ""
