DATABASE_FILE_NAME = "data/database.csv"
DATABASE_INDEX_NAME = 0
DATABASE_INDEX_EMAIL_ADDRESS = 1
DATABASE_INDEX_PHONE_NO = 2

EMAIL_API_STMP_HOST = "smtp-mail.outlook.com"
EMAIL_API_SMTP_PORT = 587
EMAIL_API_EMAIL_ADDRESS = "muhammedtiftikci@outlook.com"
EMAIL_API_EMAIL_PASSWORD = ""

SMS_API_USERNAME = ""
SMS_API_ORIGINATOR = ""
SMS_API_PASSWORD = ""